/**
 * Created by Note_Bezdvor on 28.03.2018.
 */
var str = [{"name":"Густырь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":100,"img":"images/01.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Плотва","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":200,"img":"images/02.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Чехонь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":300,"img":"images/03.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Карась","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":400,"img":"images/04.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Сом","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":500,"img":"images/05.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Налим","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":600,"img":"images/06.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Щука","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":700,"img":"images/07.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Красноперка","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":800,"img":"images/08.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Лящ","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":900,"img":"images/09.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Окунь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1000,"img":"images/10.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Камбала","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1100,"img":"images/11.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Угрь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1200,"img":"images/12.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Язь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1300,"img":"images/13.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Рыбец","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1400,"img":"images/14.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Пузанок","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1500,"img":"images/15.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Мойва","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1600,"img":"images/16.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Лосось","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1700,"img":"images/17.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Форель","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1800,"img":"images/18.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Бычок","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":1900,"img":"images/19.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Пескарь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":2000,"img":"images/20.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Сельдь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":2100,"img":"images/21.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Линь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":2200,"img":"images/22.png","present":"stock available  / No","add":"Add to cart"},
    {"name":"Стерлядь","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":2300,"img":"images/23.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Амур","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":2400,"img":"images/24.png","present":"stock available  / Yes","add":"Add to cart"},
    {"name":"Жерех","description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, aspernatur atque dicta distinctio dolore enim, eos ex ipsa iusto laboriosam necessitatibus nesciunt, obcaecati perspiciatis quas quibusdam reprehenderit soluta voluptates? Cumque.","price":2500,"img":"images/25.png","present":"stock available  / Yes","add":"Add to cart"}
]
